package com.MSIL.TestUtils;

public class Properties
{
	
	public static final String ENVIRONMENT = "environment";
	public static final String ACTION = "action";
	public static final String SSL = "ssl";
	public static final String CSV_FILE_MSIL = "csvFileName_msil_template";
	public static final String CSV_FILE_PARTNER = "csvFileName_partner";
	public static final String CSV_FILE_SVM = "csvFileName_svm";
	public static final String CSV_FILE_DMS_PRICE_MAPPING = "csvFileName_dms_price_mapping";	
	public static final String LOCAL_URL = "LOCAL_URL";
	public static final String LOCAL_USERNAME = "LOCAL_USERNAME";
	public static final String LOCAL_PASSWORD = "LOCAL_PASSWORD";
	public static final String DEV_URL = "DEV_URL";
	public static final String DEV_USERNAME = "DEV_USERNAME";
	public static final String DEV_PASSWORD = "DEV_PASSWORD";
	public static final String QA_URL = "QA_URL";
	public static final String QA_PAYMENT_USERNAME = "QA_PAYMENT_USERNAME";
	public static final String QA_PAYMENT_PASSWORD = "QA_PAYMENT_PASSWORD";
	public static final String QA_COMMON_MASTERDATA_USERNAME = "QA_COMMON_MASTERDATA_USERNAME";
	public static final String QA_COMMON_MASTERDATA_PASSWORD = "QA_COMMON_MASTERDATA_PASSWORD";
	public static final String QA_COMMON_USER_MANAGEMENT_USERNAME = "QA_COMMON_USER_MANAGEMENT_USERNAME";
	public static final String QA_COMMON_USER_MANAGEMENT_PASSWORD = "QA_COMMON_USER_MANAGEMENT_PASSWORD";
	public static final String QA_SUBSCRIBE_VEHICLE_MANAGEMENT_USERNAME = "QA_SUBSCRIBE_VEHICLE_MANAGEMENT_USERNAME";
	public static final String QA_SUBSCRIBE_VEHICLE_MANAGEMENT_PASSWORD = "QA_SUBSCRIBE_VEHICLE_MANAGEMENT_PASSWORD";
	public static final String QA_COMMON_CUSTOMER_USERNAME = "QA_COMMON_CUSTOMER_USERNAME";
	public static final String QA_COMMON_CUSTOMER_PASSWORD = "QA_COMMON_CUSTOMER_PASSWORD";
	public static final String QA_PARTNER_ACL_USERNAME = "QA_PARTNER_ACL_USERNAME";
	public static final String QA_PARTNER_ACL_PASSWORD = "QA_PARTNER_ACL_PASSWORD";
	public static final String HOTFIX_URL = "HOTFIX_URL";
	public static final String HOTFIX_USERNAME = "HOTFIX_USERNAME";
	public static final String HOTFIX_PASSWORD = "HOTFIX_PASSWORD";
	public static final String PREPROD_URL = "PREPROD_URL";
	public static final String PREPROD_PAYMENT_USERNAME = "PREPROD_PAYMENT_USERNAME";
	public static final String PREPROD_PAYMENT_PASSWORD = "PREPROD_PAYMENT_PASSWORD";
	public static final String PREPROD_PARTNER_ACL_USERNAME = "PREPROD_PARTNER_ACL_USERNAME";
	public static final String PREPROD_PARTNER_ACL_PASSWORD = "PREPROD_PARTNER_ACL_PASSWORD";
	public static final String PREPROD_SUBSCRIBE_VEHICLE_MANAGEMENT_USERNAME = "PREPROD_SUBSCRIBE_VEHICLE_MANAGEMENT_USERNAME";
	public static final String PREPROD_SUBSCRIBE_VEHICLE_MANAGEMENT_PASSWORD = "PREPROD_SUBSCRIBE_VEHICLE_MANAGEMENT_PASSWORD";
	public static final String PREPROD_COMMON_MASTERDATA_USERNAME = "PREPROD_COMMON_MASTERDATA_USERNAME";
	public static final String PREPROD_COMMON_MASTERDATA_PASSWORD = "PREPROD_COMMON_MASTERDATA_PASSWORD";
	public static final String PREPROD_COMMON_USER_MANAGEMENT_USERNAME = "PREPROD_COMMON_USER_MANAGEMENT_USERNAME";
	public static final String PREPROD_COMMON_USER_MANAGEMENT_PASSWORD = "PREPROD_COMMON_USER_MANAGEMENT_PASSWORD";
	public static final String PROD_URL = "PROD_URL";
	public static final String PROD_PAYMENT_USERNAME = "PROD_PAYMENT_USERNAME";
	public static final String PROD_PAYMENT_PASSWORD = "PROD_PAYMENT_PASSWORD";
	public static final String PROD_PARTNER_ACL_USERNAME = "PROD_PARTNER_ACL_USERNAME";
	public static final String PROD_PARTNER_ACL_PASSWORD = "PROD_PARTNER_ACL_PASSWORD";
	public static final String PROD_SUBSCRIBE_VEHICLE_MANAGEMENT_USERNAME = "PROD_SUBSCRIBE_VEHICLE_MANAGEMENT_USERNAME";
	public static final String PROD_SUBSCRIBE_VEHICLE_MANAGEMENT_PASSWORD = "PROD_SUBSCRIBE_VEHICLE_MANAGEMENT_PASSWORD";
	public static final String PROD_SUBSCRIBE_BOOKING_MANAGEMENT_USERNAME = "PROD_SUBSCRIBE_BOOKING_MANAGEMENT_USERNAME";
	public static final String PROD_SUBSCRIBE_BOOKING_MANAGEMENT_PASSWORD = "PROD_SUBSCRIBE_BOOKING_MANAGEMENT_PASSWORD";
	public static final String PROD_COMMON_USER_MANAGEMENT_USERNAME = "PROD_COMMON_USER_MANAGEMENT_USERNAME";
	public static final String PROD_COMMON_USER_MANAGEMENT_PASSWORD = "PROD_COMMON_USER_MANAGEMENT_PASSWORD";
	public static final String PROD_COMMON_MASTERDATA_USERNAME = "PROD_COMMON_MASTERDATA_USERNAME";
	public static final String PROD_COMMON_MASTERDATA_PASSWORD = "PROD_COMMON_MASTERDATA_PASSWORD";

}
